#ifndef TELECLASSIC26_VERSION_H
#define TELECLASSIC26_VERSION_H

#define TELECLASSIC26_VERSION_MAJOR 0
#define TELECLASSIC26_VERSION_MINOR 1
#define TELECLASSIC26_VERSION_PATCH 0

#endif /* TELECLASSIC26_VERSION_H */
