#ifndef TELECLASSIC26_GAMEPLAY_BLOCKS_H
#define TELECLASSIC26_GAMEPLAY_BLOCKS_H

// TeleClassic26 block IDs

// Define all built in minecraft classic blocks
#define TELECLASSIC26_BLOCK_AIR 0
#define TELECLASSIC26_BLOCK_STONE 1
#define TELECLASSIC26_BLOCK_GRASS 2
#define TELECLASSIC26_BLOCK_DIRT 3
#define TELECLASSIC26_BLOCK_COBBLESTONE 4
#define TELECLASSIC26_BLOCK_WOOD 5
#define TELECLASSIC26_BLOCK_SHRUB 6
#define TELECLASSIC26_BLOCK_BEDROCK 7
#define TELECLASSIC26_BLOCK_WATER 8
#define TELECLASSIC26_BLOCK_WATER_STILL 9
#define TELECLASSIC26_BLOCK_LAVA 10
#define TELECLASSIC26_BLOCK_LAVA_STILL 11
#define TELECLASSIC26_BLOCK_SAND 12
#define TELECLASSIC26_BLOCK_GRAVEL 13
#define TELECLASSIC26_BLOCK_GOLD_ORE 14
#define TELECLASSIC26_BLOCK_IRON_ORE 15
#define TELECLASSIC26_BLOCK_COAL 16
#define TELECLASSIC26_BLOCK_TRUNK 17
#define TELECLASSIC26_BLOCK_LEAF 18
#define TELECLASSIC26_BLOCK_SPONGE 19
#define TELECLASSIC26_BLOCK_GLASS 20
#define TELECLASSIC26_BLOCK_RED 21
#define TELECLASSIC26_BLOCK_ORANGE 22
#define TELECLASSIC26_BLOCK_YELLOW 23
#define TELECLASSIC26_BLOCK_LIGHT_GREEN 24
#define TELECLASSIC26_BLOCK_GREEN 25
#define TELECLASSIC26_BLOCK_AQUA_GREEN 26
#define TELECLASSIC26_BLOCK_CYAN 27
#define TELECLASSIC26_BLOCK_LIGHT_BLUE 28
#define TELECLASSIC26_BLOCK_BLUE 29
#define TELECLASSIC26_BLOCK_PURPLE 30
#define TELECLASSIC26_BLOCK_LIGHT_PURPLE 31
#define TELECLASSIC26_BLOCK_PINK 32
#define TELECLASSIC26_BLOCK_DARK_PINK 33
#define TELECLASSIC26_BLOCK_DARK_GREY 34
#define TELECLASSIC26_BLOCK_LIGHT_GREY 35
#define TELECLASSIC26_BLOCK_WHITE 36
#define TELECLASSIC26_BLOCK_YELLOW_FLOWER 37
#define TELECLASSIC26_BLOCK_RED_FLOWER 38
#define TELECLASSIC26_BLOCK_MUSHROOM 39
#define TELECLASSIC26_BLOCK_RED_MUSHROOM 40
#define TELECLASSIC26_BLOCK_GOLD_SOLID 41
#define TELECLASSIC26_BLOCK_IRON_SOLID 42
#define TELECLASSIC26_BLOCK_STAIRS_FULL 43
#define TELECLASSIC26_BLOCK_STAIRS_STEP 44
#define TELECLASSIC26_BLOCK_BRICK 45
#define TELECLASSIC26_BLOCK_TNT 46
#define TELECLASSIC26_BLOCK_BOOK_CASE 47
#define TELECLASSIC26_BLOCK_MOSSY_COBBLE 48
#define TELECLASSIC26_BLOCK_OBSIDIAN 49

// Define all custom blocks at CPE level 1 support
#define TELECLASSIC26_CPE_BLOCK_COBBLESTONE_SLAB 50
#define TELECLASSIC26_CPE_BLOCK_ROPE 51
#define TELECLASSIC26_CPE_BLOCK_SANDSTONE 52
#define TELECLASSIC26_CPE_BLOCK_SNOW 53
#define TELECLASSIC26_CPE_BLOCK_FIRE 54
#define TELECLASSIC26_CPE_BLOCK_LIGHT_PINK 55
#define TELECLASSIC26_CPE_BLOCK_FOREST_GREEN 56
#define TELECLASSIC26_CPE_BLOCK_BROWN_WOOL 58
#define TELECLASSIC26_CPE_BLOCK_DEEP_BLUE 58
#define TELECLASSIC26_CPE_BLOCK_TURQUOISE 59
#define TELECLASSIC26_CPE_BLOCK_ICE 60
#define TELECLASSIC26_CPE_BLOCK_CERAMIC_TILE 61
#define TELECLASSIC26_CPE_BLOCK_MAGMA 62
#define TELECLASSIC26_CPE_BLOCK_PILLAR 63
#define TELECLASSIC26_CPE_BLOCK_CRATE 64
#define TELECLASSIC26_CPE_BLOCK_STONE_BRICK 65

#endif